### ISSUE TITLE
Add administrator authentication

### ISSUE THREAD

**Issue by nicolas-bastien** [smartbooster/sandbox#1]
Implement administrators and add login / logout action.

## Tasks

- [ ] login screen
- [ ] security
- [ ] administrators CRUD

**Comment by nicolas-bastien** [comment]
@mathieu-ducrot I let you finish the administrator CRUD

- edit
- show

**Comment by mathieu-ducrot** [comment]
@nicolas-bastien you can check all the related PR to complete this issue.
